Two bugs fixes
Bug # 1:  Using NULL to replace the pybind11::capsule in py::array constructor doesn't seem to be supported in newer pybind11 version.
It was replaced by  py::capsule object which should be compatible with old and new pybind versions.

Bug #2 :
Importing python's decimal library induced a
ImportError: DLL load failed while importing acorrs_wrapper: A dynamic link library (DLL) initialization routine failed. when importing the library.

From what I understand from https://pybind11.readthedocs.io/en/stable/advanced/embedding.html 's documentation
we should avoid importing python libraries like this as the defined behavior is to only do imports inside an instance of an interpreter.

To fix the bug I simply removed the use of Decimal and replaced with strings as they can always be converted in python when receiving the array.